### PR TITLE
Check dependencies

### PR DESCRIPTION
**Pull request by jan-janssen**
Compare to https://github.com/PyCQA/astroid/blob/master/astroid/__pkginfo__.py

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
The windows tests fail with: 
```
2020-03-11T11:02:54.8554755Z ERROR conda.core.link:_execute(568): An error occurred while installing package 'conda-forge::pkginfo-1.5.0.1-py_0'.
2020-03-11T11:02:54.8555852Z CondaError: Cannot link a source that does not exist. C:\Miniconda\Scripts\conda.exe
2020-03-11T11:02:54.8556673Z Running `conda clean --packages` may resolve your problem.
2020-03-11T11:02:54.8566878Z Attempting to roll back.
2020-03-11T11:02:54.8567886Z 
2020-03-11T11:03:02.3115593Z Rolling back transaction: ...working... done
2020-03-11T11:03:02.3263647Z 
2020-03-11T11:03:02.3265706Z CondaError: Cannot link a source that does not exist. C:\Miniconda\Scripts\conda.exe
2020-03-11T11:03:02.3266837Z Running `conda clean --packages` may resolve your problem.
```

**Comment by jan-janssen** [comment]
The failing windows tests are related to https://github.com/conda-forge/conda-smithy/pull/1250

**Comment by jjhelmus** [comment]
six and wrapt are specified in the upstream project as `six~=1.12` and `wrapt~=1.11`.  `~=` are compatible release clauses as defined in [PEP 440](https://www.python.org/dev/peps/pep-0440/#compatible-release).  From my understanding these should be expressed as `six >=1.12,<2` and `wrapt >=1.11,<2` in the conda recipe.

**Comment by jan-janssen** [comment]
But pip check complains when `wrapt~=1.11` is specified and the current version is `wrapt=1.12`

**Comment by jjhelmus** [comment]
> But pip check complains when `wrapt~=1.11` is specified and the current version is `wrapt=1.12`

The astroid 2.3.3 release has the wrapt requirement as `wrapt==1.11.*`.  The master branch has the compatible release clause which was introduced in PyCQA/astroid#756

So wrapt is fine as it currently stands but `six` should be relaxed to `six >=1.12,<2`

**Comment by jan-janssen** [comment]
@jjhelmus Can you merge this PR?

**Pull request merged**
